# This workflow will do a clean install of the repo and node dependencies, and restart the node service
# this workflow is designed to work with the server of LordAkkaron#0876

name: Deploy

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy the nodejs app
              uses: appleboy/ssh-action@v0.1.2
              with:
                  host: ${{secrets.SSH_HOST}}
                  key: ${{secrets.SSH_KEY}}
                  username: ${{secrets.SSH_USERNAME}}

                  script: |
                      systemctl stop toland
                      cd ~/../srv/node
                      rm -r toland
                      git clone https://AndiZandi:${{secrets.ACCESS_TOKEN}}@github.com/D2Sanctuary/Toland.git
                      cd toland
                      npm install
                      sudo dos2unix ./src/index.js
                      chmod 777 ./src/index.js
                      echo 'BOT_TOKEN=${{secrets.BOT_TOKEN}}' > ./.env
                      systemctl start toland
                      echo 'Deployment succesful'
